development:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:80"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    dwc_services: "http://dwc_services:80"
test:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:80"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    dwc_services: "http://dwc_services:80"
homolog:
    lang: "pt"
    base: "/occurrences"
    couchdb: 'http://jb048.jbrj.gov.br:5984'
    connect: 'http://$HOST/connect'
    connect_url: 'http://$HOST/connect'
    elasticsearch: 'http://jb048.jbrj.gov.br:9200'
    dwc_services: "http://$HOST/dwc_services"
    assessments_url: "http://$HOST/assessments"
    profiles_url: "http://$HOST/profiles"
production:
    lang: "pt"
    base: "/occurrences"
    couchdb: 'http://jb049.jbrj.gov.br:5984'
    connect: 'http://$HOST/connect'
    connect_url: 'http://$HOST/connect'
    elasticsearch: 'http://jb049.jbrj.gov.br:9200'
    dwc_services: "http://$HOST/dwc_services"
    assessments_url: "http://$HOST/assessments"
    profiles_url: "http://$HOST/profiles"
