development:
    etcd: "http://localhost:4001"
    lang: "pt"
    base: ""
test:
    etcd: "http://localhost:4001"
    lang: "pt"
    base: ""
production:
    etcd: "http://cncflora.jbrj.gov.br/etcd"
    lang: "pt"
    base: "/occurrences"
