development:
    lang: "pt"
    base: ""
    couchdb: "http://couchdb:5984"
    connect: "http://connect:80"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://elasticsearch:9200"
    dwc_services: "http://dwc_services:8181"
test:
    lang: "pt"
    base: ""
    couchdb: "http://localhost:5984"
    connect: "http://localhost:8080"
    connect_url: "http://localhost:8080"
    elasticsearch: "http://localhost:9200"
    dwc_services: "http://localhost:8181"
production:
    lang: "pt"
    base: "/occurrences"
    couchdb: "http://$HOST/couchdb"
    connect: "http://$HOST/connect"
    connect_url: "http://$HOST/connect"
    elasticsearch: "http://$HOST/elasticsearch"
    dwc_services: "http://$HOST/dwc_services"
    assessments: "http://$HOST/assessments"
    assessments_url: "http://$HOST/assessments"
    profiles: "http://$HOST/profiles"
    profiles_url: "http://$HOST/profiles"
