development:
    etcd: "http://localhost:4001"
    lang: "pt"
    base: ""
test:
    etcd: "http://localhost:4001"
    lang: "pt"
    base: ""
production:
    etcd: "http://$HOST/etcd"
    lang: "pt"
    base: "/occurrences"
