occurrences:
    build: "."
    ports:
        - 8081:80
    volumes:
        - .:/opt/app
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - dwcservices:dwc_services
    environment:
        - RACK_ENV=development
elasticsearch:
    image: cncflora/elasticsearch
    ports:
        - "9200"
    volumes:
        - "/var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw"
couchdb:
    image: cncflora/couchdb
    ports:
        - "5984:5984"
        - "9001"
    volumes:
        - "/var/data/couchdb:/var/lib/couchdb:rw"
    links:
        - "elasticsearch:elasticsearch"
connect:
    image: cncflora/connect
    ports:
        - "8080:80"
    volumes:
        - "/var/data/connect:/var/floraconnect:rw"
dwcservices:
    image: cncflora/dwc-services
    ports:
        - "80"
floradata:
    image: cncflora/floradata
    environment:
        SERVICE_80_CHECK_HTTP: /api/v1/families
    ports:
        - "8181:80"
        - "9005:9001"
checklist:
    image: cncflora/checklist
    ports:
        - "8000:80"
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - floradata:floradata
    environment:
        RACK_ENV: development
