default:
    paths:
        features: "../features"
        bootstrap: "../features/bootstrap"
    context:
        class: 'FeatureContext'
    extensions:
        Behat\MinkExtension\Extension:
            base_url: http://occurrences
            default_session: selenium2
            selenium2:
                wd_host: "http://selenium:4444/wd/hub"

